# https://www.mkdocs.org/user-guide/configuration/
site_name: GreenGraph Documentation
repo_url: https://github.com/michaelweinold/greengraph
copyright: © Paul Scherrer Institute (PSI) | Code under MIT License
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Related Projects: 'related.md'
  - Theory:
    - Notation and Diagrams: 'theory/notation.md'
    - Hybrid Life-Cycle Assessment: 'theory/hlca.md'
    - Hybrid Matrix Calculations: 'theory/calculations.md'
  - Architecture:
    - Overview: 'architecture/overview.md'
  - Practice:
    - Getting Started: 'practive/gettingstarted.md'
    - Working with the Graph: 'practice/graph.md'
  - API Reference:
  #  - Concordance: 'api/concordance.md'
  #  - Characterization: 'api/characterization.md'
    - Core: 'api/core.md'
    - Math: 
      - Matrix: 'api/math/matrix.md'
      - Graph: 'api/math/graph.md'
    - Import:
      - Databases:
        - Generic: 'api/importers/databases/generic.md'
        - Ecoinvent: 'api/importers/databases/ecoinvent.md'
        - InputOutput: 'api/importers/databases/inputoutput.md'
      - Charactization Methods:
        - Generic: 'api/importers/characterization/generic.md'
        - IMPACT World +: 'api/importers/characterization/iwp.md'
    - Utility:
      - Graph: 'api/utility/graph.md'
theme: # https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs
  name: material
  custom_dir: docs/_overrides
  logo: _logos/logo_greengraph.svg
  favicon: _logos/logo_greengraph.svg
  highlightjs: true
  navigation_depth: 4
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.footnote.tooltips
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mermaid2
  - mkdocstrings:
        handlers:
          python:
            options:
              docstring_style: numpy
              show_root_toc_entry: True
              show_root_heading: true
              heading_level: 2
              show_source: true
              filters: []
              separate_signature: true

  - markdown-exec
  #- autorefs
  - include-markdown
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: false

extra_javascript:
  - _javascripts/katex.js
  # https://cdnjs.com/libraries/KaTeX
  # unpkg is incredibly slow (17s to load the css file)
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
extra_css:
  # https://cdnjs.com/libraries/KaTeX
  # unpkg is incredibly slow (17s to load the css file)
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - _css/extra.css

watch:
  - greengraph

extra:
  generator: false